runtime: python38 # or python37 for Python 3.7
service: portafolio-backend-api

instance_class: F1

entrypoint: gunicorn -w 4 -b 0.0.0.0:5000 main:app

runtime_config:
  python_version: 3

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto