runtime: python38 # or python37 for Python 3.7
service: portafolio-backend-api

instance_class: F1

#entrypoint: gunicorn wsgi:app -w 2 -b :5000 --timeout 120
entrypoint: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:application

runtime_config:
  python_version: 3

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto