dbCodes = {
  'ORA-00001': "Ya existe un registro con ese ID / PK",
  'ORA-00257': "Error interno de la base de datos",
  'ORA-00600': "Error interno de la base de datos",
  'ORA-00904': "Error al ejecutar el comando, identificador no válido",
  'ORA-00905': "missing keyword",
  'ORA-00911': "Caracter inválido",
  'ORA-00913': "Demasiados valores",
  'ORA-00918': "Error al ejecutar el comando, columna mal definida",
  'ORA-00933': "Sentencia SQL no válida",
  'ORA-00936': "missing expression",
  'ORA-00947': "Error al ejecutar el comando, faltan valores",
  'ORA-00984': "Columna no autorizada",
  'ORA-01003': "no statement parsed",
  'ORA-01008': "not all variables bound",
  'ORA-01031': "Privilegios insuficiente",
  'ORA-01033': "Inicialización o apagado de ORACLE DB en proceso",
  'ORA-01422': "La consulta ha regresado más de un valor",
  'ORA-01722': "Número inválido",
  'ORA-01775': "looping chain of synonyms",
  'ORA-01843': "No es un mes válido",
  'ORA-01861': "literal does not match format string",
  'ORA-03113': "end-of-file on communication channel",
  'ORA-04031': "unable to allocate string bytes of shared memory",
  'ORA-06413': "La conexión no está disponible",
  'ORA-06502': "PL/SQL: numeric or value error string",
  'ORA-06508': "PL/SQL: could not find program unit being called",
  'ORA-06512': "at string line string",
  'ORA-28000': "La cuenta está bloqueada",
  'ORA-30036': "unable to extend segment by string in undo tablespace 'string'"
}